import { create } from 'zustand'

const mockProducts = [
  
  {
    id: 1,
    nombre: '212 VIP',
    marca: 'Carolina Herrera',
    precio: 440.000,
    descuento: 15,
    imagen: '/images/mujer/212VIPD.webp',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Oriental',
    volumen: 90,
    notaSalida: ' ron y maracuyá (fruta de la pasión)',
    notaCorazon: 'gardenia y almizcle',
    notaBase: 'vainilla y haba tonka',
    stock: 12,
    descripcion: 'Es una fragancia glamorosa y seductora.',
    resenas: 189
  },
  {
    id: 2,
    nombre: 'Olimpea',
    marca: 'Paco Rabanne',
    precio: 420.000,
    descuento: 10,
    imagen: '/images/mujer/OLIMPEA.jpg',
    rating: 5.0,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 120,
    notaSalida: 'Jazmín de agua,Mandarina verde, Flor de jengibre ',
    notaCorazon: ' vainilla salada y notas acuáticas florales.',
    notaBase: ' ámbar gris, cachemira y sándalo',
    stock: 12,
    descripcion: 'un aroma audaz y sensual que combina notas de vainilla salada con jazmín de agua, mandarina verde y madera de cachemira, creando un efecto "diosa" .',
    resenas: 428
  },
  {
    id: 3,
    nombre: 'Omnia Coral',
    marca: 'Bvlgari',
    precio: 380.000,
    descuento: 0,
    imagen: '/images/mujer/OCORAL.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral Frutal',
    volumen: 75,
    notaSalida: 'Bergamota y bayas de goji',
    notaCorazon: '(florales y exóticas): Nenúfar (lirio de agua), hibisco y granada.',
    notaBase: '(suaves y amaderadas): Almizcle y cedro de Virginia.',
    stock: 10,
    descripcion: 'Es una fragancia para mujeres lanzadas, fresca vibrante y alegre.',
    resenas: 267
  },
  {
    id: 4,
    nombre: 'Black XS',
    marca: 'Paco Rabanne',
    precio: 430.000,
    descuento: 0,
    imagen: '/images/mujer/blackxs.jpg',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ': Arándano, pimienta rosa y tamarindo.',
    notaCorazon: 'Rosa de eléboro, violeta negra y flor del cacao.',
    notaBase: 'Madera de massoia, pachulí y vainilla negra.',
    stock: 12,
    descripcion: 'Black XS es un elixir rebelde y seductor, una poción oriental amaderada que fusiona arándanos ácidos y pimienta rosa con un corazón oscuro de rosa eléboro y cacao. Es la fragancia de la sensualidad rockera, diseñada para almas impertinentes que aman la vainilla negra y los acordes intensos',
    resenas: 198
  },
  {
    id: 5,
    nombre: 'La Bomba',
    marca: 'Carolina Herrera',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/mujer/BOMBA.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 90,
    notaSalida: 'Pitaya roja que brinda un inicio tropical y vibrante.',
    notaCorazon: ' Peonía cereza  y frangipani, ofreciendo una mezcla floral exuberante.',
    notaBase: 'Vainilla y pachulí, que proporcionan una estela cálida, duradera y sofisticada.',
    stock: 22,
    descripcion: 'es una declaración de intenciones: atrevida, alegre y sin complejos. Representa la metamorfosis y la autenticidad, invitando a las mujeres a "desplegar sus alas" y vivir con intensidad..',
    resenas: 267
  },
  {
    id: 6,
    nombre: 'Good Girl',
    marca: 'Carolina Herrera',
    precio: 390.000,
    descuento: 0,
    imagen: '/images/mujer/GOODGIRL.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Oriental',
    volumen: 80,
    notaSalida: 'Almendra y café',
    notaCorazon: 'Jazmín sambac y nardos',
    notaBase: 'Haba tonka, cacao, vainilla y sándalo',
    stock: 8,
    descripcion: 'es un susurro de jazmín blanco que se vuelve grito con el cacao intenso, una sinfonía de luz y sombra.',
    resenas: 389
  },
  {
    id: 7,
    nombre: 'Candy Prada',
    marca: 'Prada',
    precio: 410.000,
    descuento: 10,
    imagen: '/images/mujer/CANDYPRADA.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Oriental',
    volumen: 80,
    notaSalida: 'Caramelo',
    notaCorazon: ' Almizcle y notas atalcadas',
    notaBase: 'Benjuí y vainilla',
    stock: 7,
    descripcion: 'es para la mujer que se atreve a ser juguetona, sexy y peligrosamente chic, celebrando la adicción a la dulzura con una elegancia inconfundiblemente.',
    resenas: 234
  },
  {
    id: 8,
    nombre: 'Chance',
    marca: 'Chanel',
    precio: 490.000,
    descuento: 0,
    imagen: '/images/mujer/CHANCE.png',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Chipre  ',
    volumen: 100,
    notaSalida: ' Pimienta rosa.',
    notaCorazon: 'Jazmín e iris.',
    notaBase: 'Pachulí, almizcle blanco y vainilla.',
    stock: 4,
    descripcion: 'Más que un perfume, es la "suerte" que se provoca y se lleva puesta. Es la creencia en la felicidad y el optimismo hecho aroma.',
    resenas: 512
  },
  {
    id: 9,
    nombre: '212 Vip Rose',
    marca: 'Carolina Herrera',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/mujer/212VIPROSE.png',
    rating: 4.7,
    genero: 'mujer',
    tipo: ' floral',
    volumen: 100,
    notaSalida: 'Champaña rosé y notas afrutadas.',
    notaCorazon: 'Flor del duraznero y rosa.',
    notaBase: ' Almizcle blanco, notas amaderadas y ámbar.',
    stock: 10,
    descripcion: 'Es una fragancia versátil, adecuada para diversas ocasiones, que combina un estilo vibrante con actitud.',
    resenas: 289
  },
  {
    id: 10,
    nombre: 'Delilah',
    marca: 'Maison Alhambra',
    precio: 280.000,
    descuento: 10,
    imagen: '/images/mujer/DELILA.jpg',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Ruibarbo, lichi y bergamota.',
    notaCorazon: 'Rosa turca, peonía y lirio de los valles (azucena).',
    notaBase: 'Almizcle blanco, vainilla y madera de cachemira',
    stock: 18,
    descripcion: ' Para la mujer que busca destacar con un aroma que es, a la vez, delicado y seductor, perfecto para el uso diario o una ocasión especial.',
    resenas: 345
  },
  {
    id: 11,
    nombre: 'Coco Mademoiselle',
    marca: 'Chanel',
    precio: 780.000,
    descuento: 0,
    imagen: '/images/mujer/COCOM.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Naranja siciliana, bergamota de Calabria y limón.',
    notaCorazon: 'Rosa, jazmín y toques afrutados.',
    notaBase: 'Pachulí, vetiver, vainilla de Madagascar, haba tonka y almizcle blanco',
    stock: 2,
    descripcion: 'Es una declaración de libertad, elegancia y sensualidad indomable, ideal para la mujer que se reinventa constantemente..',
    resenas: 278
  },
  {
    id: 12,
    nombre: 'Q',
    marca: 'Dolce & Gabbana',
    precio: 450.000,
    descuento: 10,
    imagen: '/images/mujer/QG.png',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Limón siciliano, naranja sanguínea y jazmín.',
    notaCorazon: 'Cereza y heliotropo',
    notaBase: 'Madera de cedro y almizcle.',
    stock: 10,
    descripcion: 'es una fragancia vibrante y sofisticada que evoca a una reina moderna.',
    resenas: 312
  },
  {
    id: 13,
    nombre: 'Yara Candy',
    marca: 'Lattafa',
    precio: 230.000,
    descuento: 10,
    imagen: '/images/mujer/YARAC.png',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Gourmand',
    volumen: 100,
    notaSalida: 'Grosellas negras y mandarina verde.',
    notaCorazon: 'Caramelo de fresa y gardenia.',
    notaBase: 'Vainilla, almizcle, ámbar y sándalo.',
    stock: 18,
    descripcion: 'Es una fragancia ideal para la mujer moderna, alegre y soñadora, perfecta para días primaverales.',
    resenas: 423
  },
  {
    id: 14,
    nombre: 'Very Good Girl',
    marca: 'Carolina Herrera',
    precio: 440.000,
    descuento: 10,
    imagen: '/images/mujer/VERYGOODGIRL.png',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 80,
    notaSalida: ' Lichi y grosella roja',
    notaCorazon: 'Rosa.',
    notaBase: 'Vainilla Bourbon y vetiver.',
    stock: 6,
    descripcion: ' fragancia ideal para mujeres que abrazan su dualidad: dulces y decididas, clásicas y atrevidas.',
    resenas: 267
  },
  {
    id: 15,
    nombre: 'Donna Valentino',
    marca: 'Valentino',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/mujer/VADONNA.jpg',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Bergamota',
    notaCorazon: ' Iris y Rosa de Bulgaria.',
    notaBase: 'Cuero, Pachulí y Vainilla',
    stock: 7,
    descripcion: 'Es una fragancia que, en cada rocío, celebra la belleza natural y la sofisticación refinada.',
    resenas: 234
  },
  {
    id: 16,
    nombre: 'Rose Rush',
    marca: 'Paris Hilton',
    precio: 290.000,
    descuento: 0,
    imagen: '/images/mujer/RoseRush.jpg',
    rating: 4.6,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Pétalos de rosa, lichi y neroli.',
    notaCorazon: 'Rosa de mayo, papaya y peonía.',
    notaBase: 'Almizcle blanco, ámbar y cedro.',
    stock: 8,
    descripcion: 'Es un amanecer rosado embotellado, un velo de pétalos que despierta con la frescura del lichi y la caricia del neroli, Romántica, seductora, femenina, moderna.',
    resenas: 198
  },
  {
    id: 17,
    nombre: 'CH',
    marca: 'Carolina Herrera',
    precio: 440.000,
    descuento: 20,
    imagen: '/images/mujer/CHD.jpg',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Bergamota, toronja, limón de Amalfi, melón y notas acuáticas.',
    notaCorazon: 'Jazmín, rosa búlgara, praliné, canela y flor del naranjo.',
    notaBase: 'Almizcares, Cedro',
    stock: 6,
    descripcion: 'Es una fragancia versátil, considerada elegante y moderna, perfecta para la oficina o el uso diario, con buena duración.',
    resenas: 289
  },
  {
    id: 18,
    nombre: 'Jean Paul Gaultier Classic',
    marca: 'Jean Paul Gaultier',
    precio: 430.000,
    descuento: 10,
    imagen: '/images/mujer/JPGC.png',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Flor de azahar, anís estrellado, rosa, mandarina, pera, bergamota.',
    notaCorazon: 'Jengibre, orquídea, ylang-ylang, iris, nardos, ciruela',
    notaBase: 'Vainilla, ámbar, almizcle, canela, sándalo',
    stock: 8,
    descripcion: ' Sensual, icónico y atalcado, Es considerada una fragancia atemporal, perfecta para otoño e invierno.',
    resenas: 212
  },
  {
    id: 19,
    nombre: 'La Vie Est Belle',
    marca: 'Lancôme',
    precio: 480.000,
    descuento: 0,
    imagen: '/images/mujer/lavidaesbella.jpg',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Gourmand',
    volumen: 100,
    notaSalida:'Grosellas negras y pera.',
    notaCorazon: 'Iris, jazmín y flor de azahar del naranjo.',
    notaBase: 'Praliné, vainilla, pachulí y haba tonka.',
    stock: 10,
    descripcion: 'Representa una declaración de libertad y la elección de un camino propio hacia la felicidad.',
    resenas: 189
  },
  {
    id: 20,
    nombre: 'Bright Crystal',
    marca: 'Versace',
    precio: 380.000,
    descuento: 10,
    imagen: '/images/mujer/crysta.jpg',
    rating: 4.6,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Yuzu, granada y toques de hielo.',
    notaCorazon: 'Peonía, magnolia y flor de loto.',
    notaBase: 'Almizcle, ámbar y caoba.',
    stock: 9,
    descripcion: 'Es un aroma  para la mujer contemporánea, afrutado y delicado, que combina glamour con una frescura inigualable.',
    resenas: 167
  },
  {
    id: 21,
    nombre: 'Dylan Blue',
    marca: 'Versace',
    precio: 440.000,
    descuento: 10,
    imagen: '/images/mujer/dylanv.jpg',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Manzana Granny Smith, grosellas negras, trébol blanco, nomeolvides y shiso',
    notaCorazon: 'Durazno, petalia, rosa silvestre, rosa y jazmín.',
    notaBase: 'Almizcle, maderas blancas, styrax y pachulí.',
    stock: 6,
    descripcion: 'Es un tributo a la mujer que conoce el poder de su propia mente y sensualidad, envuelta en una joya azul profundo que evoca la mitología.',
    resenas: 276
  },
  {
    id: 22,
    nombre: 'Voce Viva',
    marca: 'Valentino',
    precio: 480.000,
    descuento: 0,
    imagen: '/images/mujer/VOCEVIVA.webp',
    rating: 5.0,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Bergamota italiana, mandarina y un toque de jengibre.',
    notaCorazon: 'Absoluto de flor de azahar del naranjo y gardenia dorada',
    notaBase: 'Acorde de musgo cristalino, vainilla y almizcle.',
    stock: 6,
    descripcion: ' Fragancia personal, íntima y potente, diseñado para celebrar la voz de la mujer.',
    resenas: 634
  },
  {
    id: 23,
    nombre: 'Tous',
    marca: 'Tous',
    precio: 360.000,
    descuento: 0,
    imagen: '/images/mujer/tous.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Bergamota, hojas de violeta, casia y cilantro',
    notaCorazon: 'Gardenia, peonía, jazmín y rosa',
    notaBase: 'Almizcle blanco, iris y cedro de Marruecos.',
    stock: 8,
    descripcion: 'Es una excelente opción para mujeres que buscan un perfume versátil, que combine frescura con una elegancia atemporal.',
    resenas: 223
  },
  {
    id: 24,
    nombre: 'Yara',
    marca: 'Lattafa',
    precio: 260.000,
    descuento: 15,
    imagen: '/images/mujer/YARA.jpg',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Heliotropo, orquídea, mandarina.',
    notaCorazon: 'Acordes gourmand, frutas tropicales',
    notaBase: 'Vainilla, almizcle, sándalo.',
    stock: 13,
    descripcion: 'Versátil, ideal para uso diario, citas y ocasiones especiales. .',
    resenas: 345
  },
  {
    id: 25,
    nombre: 'Ralph Blue',
    marca: 'Ralph Laurent',
    precio: 420.000,
    descuento: 10,
    imagen: '/images/mujer/ralphblue.jpg',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Jazmín, gardenia, flor de loto, lirio de los valles, peonía rosa y toronja.',
    notaCorazon: 'Nardos, rosa, flor de azahar, albahaca y verbena.',
    notaBase: 'Almizcle, vetiver, ámbar, sándalo, musgo de roble y ante.',
    stock: 7,
    descripcion:'fresca y sofisticada, diseñada para la mujer libre y elegante, ideal para el uso diario o momentos especiales por su equilibrio entre frescura natural y sofisticación.',
    resenas: 212
  },
  {
    id: 26,
    nombre: 'Halloween',
    marca: 'Jesus Del Pozzo',
    precio: 260.000,
    descuento: 10,
    imagen: '/images/mujer/HALLOWEEND.png',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Violeta, notas marinas, lima verde y hoja de plátano.',
    notaCorazon: 'Magnolia, nardos, violeta, pimienta y lirio de los valles.',
    notaBase: 'Sándalo, incienso, vainilla de Madagascar y mirra.',
    stock: 9,
    descripcion: 'Enigmático, romántico, juvenil y chispeante, ideal para quienes buscan un aroma distinguido pero versátil.',
    resenas: 567
  },
  {
    id: 27,
    nombre: 'Bvlgari Rose',
    marca: 'Bvlgari',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/mujer/bulgaryrose.jpg',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Rosa, granada, almizcle y bergamota.',
    notaCorazon: 'Rosa de Damasco, peonía, jazmín y durazno.',
    notaBase: 'Almizcle, sándalo, incienso y vainilla.',
    stock: 11,
    descripcion: 'Femenino, romántico y lujoso, diseñado para evocar la suavidad del oro rosa, para quienes prefieren fragancias no intrusivas.',
    resenas: 512
  },

  {
    id: 28,
    nombre: 'Haya',
    marca: 'Lattafa',
    precio: 380.000,
    descuento: 10,
    imagen: '/images/mujer/HAYA.jpg',
    rating: 5.0,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Champán, fresa, naranja tangerina, naranja sanguina y rosa',
    notaCorazon: 'Gardenia, jazmín y orquídea de vainilla.',
    notaBase: 'Ámbar, sándalo y castaña.',
    stock: 5,
    descripcion: ' alegre, juvenil y sofisticada con un aroma afrutado predominante,Versátil, ideal para climas cálidos, primavera/verano y ocasiones románticas o diurnas.',
    resenas: 789
  },
  {
    id: 29,
    nombre: 'Touch of pink',
    marca: 'Lacoste',
    precio: 380.000,
    descuento: 10,
    imagen: '/images/mujer/LACOSTED.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Naranja sanguina, naranja, durazno, cilantro y cardamomo.',
    notaCorazon: 'Jazmín, semillas de zanahoria, cilantro, hojas de violeta y cardamomo.',
    notaBase: 'Vainilla, almizcle y sándalo.',
    stock: 12,
    descripcion: 'Fresco, optimista, magnético y alegre.',
    resenas: 267
  },
  {
    id: 30,
    nombre: 'Lady Millon',
    marca: 'Paco Rabanne',
    precio: 450.000,
    descuento: 10,
    imagen: '/images/mujer/LADYD.webp',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Frambuesa, neroli y limón de Amalfi.',
    notaCorazon: 'Jazmín, flor del naranjo africano y gardenia.',
    notaBase: 'Miel blanca, pachulí y ámbar.',
    stock: 10,
    descripcion: 'Ideal para mujeres decididas y sofisticadas, adecuado para la noche y climas fríos.',
    resenas: 312
  },
  {
    id: 31,
    nombre: 'Ligth Blue',
    marca: 'Doulce & Gabbana',
    precio: 380.000,
    descuento: 0,
    imagen: '/images/mujer/Ligthblue.png',
    rating: 4.7,
    genero: 'mujer',
    tipo: 'Citrica',
    volumen: 100,
    notaSalida: ' Limón siciliano, manzana, cedro y campanilla.',
    notaCorazon: 'Bambú, jazmín y rosa blanca.',
    notaBase: 'Cedro, almizcle y ámbar.',
    stock: 7,
    descripcion:'Evoca la alegría de vivir, la frescura de sábanas limpias y la sofisticación relajada de unas vacaciones en el Mediterráneo.',
    resenas: 245
  },
  {
    id: 32,
    nombre: 'Miss Dior',
    marca: 'Christian Dior',
    precio: 400.000,
    descuento: 10,
    imagen: '/images/mujer/MISS.png',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Iris, peonía y lirio de los valles.',
    notaCorazon: 'Rosa, albaricoque y durazno.',
    notaBase: ' Vainilla, almizcle, haba tonka, sándalo y benjuí.',
    stock: 6,
    descripcion: 'Es un aroma muy agradable, elegante, suave, femenino, delicado, de niña bonita.',
    resenas: 389
  },
  {
    id: 33,
    nombre: 'Toy 2 Bubble Gum',
    marca: 'Monchino',
    precio: 380.000,
    descuento:10,
    imagen: '/images/mujer/OSO.jpg',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'chicle, frutas confitadas, naranja amarga y limón.',
    notaCorazon:'Rosa de Bulgaria, durazno, mora azul, flor del duraznero, canela y jengibre.',
    notaBase: 'Almizcle, ambroxan y cedro',
    stock: 9,
    descripcion: 'Uso diario, perfecto para climas cálidos o para añadir un toque divertido y femenino.',
    resenas: 267
  },
  {
    id: 34,
    nombre: '212 heroes',
    marca: 'Carolina Herrera',
    precio: 420.000,
    descuento: 15,
    imagen: '/images/mujer/212HEROESD.webp',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida:'Mandarina y frambuesa.',
    notaCorazon: 'Jazmín y flor de azahar del naranjo.',
    notaBase: 'Sándalo y cedro',
    stock: 8,
    descripcion:'fragancia persistente se caracteriza por su frescura y modernidad, perfecta para un uso diario.',
    resenas: 456
  },
  {
    id: 35,
    nombre: 'Toy 2',
    marca: 'Monchino',
    precio: 440.000,
    descuento: 10,
    imagen: '/images/mujer/OSO1.jpg',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Manzana, mandarina y magnolia.',
    notaCorazon: 'Grosella blanca, peonía y jazmín',
    notaBase: 'Almizcle, Amberwood y sándalo',
    stock: 11,
    descripcion: 'Fresco, cítrico, floral, elegante y versátil,combina la energía cítrica con un toque delicado de flores blancas y una base amaderada suave.',
    resenas: 334
  },
  {
    id: 36,
    nombre: 'Voce Viva',
    marca: 'Valentino',
    precio: 460.000,
    descuento: 0,
    imagen: '/images/mujer/VOCEVIVA.webp',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: ' Mandarina italiana, bergamota y jengibre.',
    notaCorazon: 'Absoluto de azahar del naranjo y gardenia dorada.',
    notaBase: 'Musgo de cristal, vainilla Bourbon, haba tonka, sándalo y almizcle.',
    stock: 8,
    descripcion: 'Diseñada para ser una declaración de feminidad, sofisticación y fuerza, celebrando la individualidad de la mujer.',
    resenas: 289
  },
  {
    id: 37,
    nombre: '9AM',
    marca: 'Afnan',
    precio: 280.000,
    descuento: 10,
    imagen: '/images/mujer/9AMD.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Citrica',
    volumen: 100,
    notaSalida: 'Mandarina, bergamota, toronja',
    notaCorazon: 'Frambuesa, grosellas negras, rosa, peonía.',
    notaBase: 'Almizcle, ámbar, naranja.',
    stock: 11,
    descripcion:'una opción ideal para jóvenes o mujeres que buscan un perfume diario con buena duración y una vibración energética',
    resenas: 278
  },
  {
    id: 38,
    nombre: '9PM',
    marca: 'Afnan',
    precio: 320.000,
    descuento: 10,
    imagen: '/images/mujer/9PMD.png',
    rating: 5.0,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: ' Frambuesa, manzana, violeta y naranja.',
    notaCorazon: 'Rosa, peonía, iris y jazmín',
    notaBase: 'Cedro, ciprés, pino y ámbar,',
    stock: 10,
    descripcion: 'Envolvente, dulce y sofisticado, ideal para ocasiones especiales y salidas nocturnas.',
    resenas: 612
  },
  {
    id: 39,
    nombre: 'Femme',
    marca: 'Hugo Boss',
    precio: 360.000,
    descuento: 0,
    imagen: '/images/mujer/femme.png',
    rating: 4.8,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Grosellas negras, fresia y mandarina',
    notaCorazon: 'Azucena, jazmín y rosa de Bulgaria.',
    notaBase: 'albaricoque, ámbar y limonero.',
    stock: 12,
    descripcion: 'Representa la feminidad moderna, siendo un perfume ligero, versátil y clásico.',
    resenas: 234
  },
  {
    id: 40,
    nombre: 'Velvet Gold',
    marca: 'Orientica',
    precio: 280.000,
    descuento: 10,
    imagen: '/images/mujer/ORIENTICA.png',
    rating: 4.9,
    genero: 'mujer',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'Caramelo, violeta, pimienta rosa y bergamota.',
    notaCorazon: ' rosa y pachulí.',
    notaBase: 'Vainilla, almizcle y  ámbar gris.',
    stock: 7,
    descripcion: 'Potente y con carácter,perfecta para otoño y eventos de noche.',
    resenas: 512
  },

  
  {
    id: 41,
    nombre: 'Sauvage',
    marca: 'Christian Dior',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/hombre/SAUVAGE.jpg',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Fougere',
    volumen: 100,
    notaSalida: 'Bergamota de Calabria y pimienta',
    notaCorazon: 'Pimienta de Sichuan, lavanda, pimienta rosa, vetiver, pachulí, geranio y elemí.',
    notaBase: 'Ambroxan, cedro y ládano.',
    stock: 5,
    descripcion: 'Es considerada una fragancia versátil, adecuada para uso diario o eventos nocturnos.', 

    resenas: 245
  },
  {
    id: 42,
    nombre: 'Eros',
    marca: 'Versace',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/EROSH.png',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Fougere',
    volumen: 100,
    notaSalida: 'Menta, manzana acaramelada, limón y mandarina.',
    notaCorazon: 'Ambroxan, geranio y esclarea.',
    notaBase: 'Vainilla, cedro, vetiver y pachulí.',
    stock: 10,
    descripcion: 'Para hombres apasionados, modernos y seguros de sí mismos, inspirada en la mitología griega.',
    resenas: 312
  },
  {
    id: 43,
    nombre: 'Just Different',
    marca: 'Hugo Boss',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/HDIFFERENT.png',
    rating: 4.6,
    genero: 'hombre',
    tipo: 'Especiada',
    volumen: 125,
    notaSalida: 'Menta helada y manzana Granny Smith.',
    notaCorazon: 'Albahaca, fresia y cilantro.',
    notaBase: 'Cachemira, pachulí, ládano e incienso de olíbano.',
    stock: 8,
    descripcion: ' es un soplo de aire helado en la ciudad de cemento,un susurro herbal que se convierte en grito creativo, dejando una estela persistente de quien no sigue reglas, sino que las crea.',
    resenas: 156
  },
  {
    id: 44,
    nombre: 'La Nuit L Homme',
    marca: 'YvesSaint Laurent',
    precio: 450.000,
    descuento: 0,
    imagen: '/images/hombre/Lanuit.png',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Cardamomo (especiada y fresca).',
    notaCorazon: 'Lavanda, cedro de Virginia y bergamota',
    notaBase: 'Vetiver y alcaravea ',
    stock: 10,
    descripcion: 'Es un susurro en la oscuridad, una danza entre la frescura especiada, la encarnación del misterio seductor .',
    resenas: 234
  },
  {
    id: 45,
    nombre: 'Boss Bottled',
    marca: 'Hugo Boss',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/HGBG.jpg',
    rating: 4.6,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: ' Manzana, ciruela, bergamota, limón, musgo de roble y geranio.',
    notaCorazon: 'Canela, caoba y clavel',
    notaBase: 'Vainilla, sándalo, cedro, vetiver y olivo.',
    stock: 8,
    descripcion: ' una versión más amaderada y ambarina, con notas de orris y raíz de higuera.',
    resenas: 312
  },
  {
    id: 46,
    nombre: 'One Million',
    marca: 'Paco Rabanne',
    precio: 460.000,
    descuento: 10,
    imagen: '/images/hombre/one.png',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Pomelo, menta y mandarina roja',
    notaCorazon: 'Rosa, canela y notas especiadas',
    notaBase: 'Cuero, ámbar, pachulí y notas amaderadas.',
    stock: 10,
    descripcion: 'es una fragancia icónica,  Se caracteriza por un aroma seductor y vibrante Es ideal para la noche y eventos especiales.',
    resenas: 456
  },
  {
    id: 47,
    nombre: 'Phantom',
    marca: 'Paco Rabanne',
    precio: 375.000,
    descuento: 0,
    imagen: '/images/hombre/PHANTON.png',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Lavanda, ralladura de limón y limón de Amalfi.',
    notaCorazon: 'Lavanda, manzana, notas terrosas, humo y pachulí.',
    notaBase: ' Vainilla, lavanda y vetiver.',
    stock: 4,
    descripcion:'Es una fragancia amaderada aromática futurista, diseñada para el hombre audaz. .',
    resenas: 267
  },
  {
    id: 48,
    nombre: 'Acqua Di Gio',
    marca: 'Giorgio Armani',
    precio: 390.000,
    descuento: 10,
    imagen: '/images/hombre/AGIO.png',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Especiada',
    volumen: 100,
    notaSalida: 'Lima, limón, bergamota, jazmín, naranja, mandarina y neroli.',
    notaCorazon: 'calone, romero, fresia, jacinto, cilantro y notas florales.',
    notaBase: 'Almizcle blanco, cedro, musgo de roble, pachulí y ámbar.',
    stock: 6,
    descripcion: 'es un susurro del Mediterráneo, una brisa fresca que fusiona notas marinas cristalinas con la calidez cítrica de la bergamota, el geranio y el romero. Su aroma evoca la libertad del océano y la fuerza de la naturaleza, convirtiéndose en un clásico atemporal.',
    resenas: 298
  },
  {
    id: 49,
    nombre: 'Bleu de Chanel',
    marca: 'Chanel',
    precio: 460.000,
    descuento: 10,
    imagen: '/images/hombre/BLUECHANEL.jpg',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Toronja, limón, menta, pimienta rosa, bergamota, aldehídos y cilantro.',
    notaCorazon: 'Jengibre, nuez moscada, jazmín y melón.',
    notaBase: 'Incienso, ámbar, cedro, sándalo, pachulí, ládano y amberwood.',
    stock: 5,
    descripcion: 'Ideal para diario, trabajo o eventos formales debido a su carácter limpio y masculino.',
    resenas: 467
  },
  {
    id: 50,
    nombre: 'Aventus',
    marca: 'Creed',
    precio: 750.000,
    descuento: 0,
    imagen: '/images/hombre/AVENTUS.png',
    rating: 5.0,
    genero: 'hombre',
    tipo: 'Chipre',
    volumen: 100,
    notaSalida: ' Bergamota, grosellas negras, manzana y piña.',
    notaCorazon: 'Abedul, pachulí, jazmín de Marruecos y rosa.',
    notaBase: 'Almizcle, musgo de roble, ambroxan y vainilla.',
    stock: 3,
    descripcion: 'Una fragancia de lujo extremo con notas frutales frescas.',
    resenas: 567
  },
  {
    id: 51,
    nombre: 'Issey Miyake',
    marca: 'Issey Miyake',
    precio: 420.000,
    descuento: 15,
    imagen: '/images/hombre/MIYAKEH.jpg',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Yuzu, limón, bergamota, cedrón',
    notaCorazon: 'Nuez moscada, canela, flor de loto, azafrán.',
    notaBase: 'Madera de sándalo, ámbar, tabaco, vetiver',
    stock: 9,
    descripcion: 'Busca capturar la serenidad y la frescura del agua con un toque elegante y natural, convirtiéndola en un aroma icónico y atemporal.',
    resenas: 278
  },
  {
    id: 52,
    nombre: '9AM',
    marca: 'Afnan',
    precio: 350.000,
    descuento: 10,
    imagen: '/images/hombre/9AMH.png',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Floral',
    volumen: 100,
    notaSalida: 'mandarina, bergamota y pomelo',
    notaCorazon: 'grosellas negras y frambuesa',
    notaBase: 'almizcle, ámbar y naranja.',
    stock: 6,
    descripcion: 'Es ideal para el uso diario en climas cálidos, ofreciendo una estela moderada.',
    resenas: 289
  },
  {
    id: 53,
    nombre: 'Valentino Born In Roma Intense',
    marca: 'Valentino',
    precio: 440.000,
    descuento: 0,
    imagen: '/images/hombre/VINTENSE.jpg',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Vainilla Bourbon y bergamota',
    notaCorazon: 'Trío de Jazmín.',
    notaBase: ' Benjuí (dulce y balsámico)',
    stock: 5,
    descripcion: 'diseñada para ser intensa, seductora y sofisticada. Se caracteriza por una mezcla potente de vainilla Bourbon, lavanda/jazmín y notas amaderadas o de benjuí.',
    resenas: 345
  },
  {
    id: 54,
    nombre: 'Bad Boy Gold Fantasy',
    marca: 'Carolina Herrera',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/hombre/boybadgold.png',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Pimienta blanca, pimienta rosa y bergamota.',
    notaCorazon: 'Esclarea (salvia), cedro y vetiver',
    notaBase: 'tonka y cacao.',
    stock: 4,
    descripcion: 'es una edición limitada coleccionable, caracterizada como una fragancia Ámbar Amaderada con un aroma intenso, dulce y especiado.',
    resenas: 234
  },
  {
    id: 55,
    nombre: 'Hugo Boss Bottled',
    marca: 'Hugo Boss',
    precio: 350.000,
    descuento: 10,
    imagen: '/images/hombre/HGBG.jpg',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Manzana, ciruela, bergamota, limón, musgo de roble y geranio.',
    notaCorazon: 'Vainilla, sándalo, cedro, vetiver y olivo.',
    notaBase: 'Cedro, Ámbar Gris',
    stock: 6,
    descripcion: 'un aroma clásico, equilibrado y versátil que combina notas frescas de manzana y cítricos con un corazón cálido de canela y un fondo amaderado de sándalo y vainilla. .',
    resenas: 389
  },
  {
    id: 56,
    nombre: 'Bharar Niche',
    marca: 'Bharraa',
    precio: 320.000,
    descuento: 0,
    imagen: '/images/hombre/NICHEBHARARA.jpg',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'floral',
    volumen: 100,
    notaSalida: 'Cítricos y enebro de Virginia.',
    notaCorazon: 'Jazmín, chocolate y abeto balsámico.',
    notaBase: 'Amberwood (madera de ámbar) y musgo.',
    stock: 3,
    descripcion: 'Destaca por su alta duración y proyección, ideal para climas frescos y ocasiones.',
    resenas: 267
  },
  {
    id: 57,
    nombre: 'Inmotion',
    marca: 'Hugo Boss',
    precio: 350.000,
    descuento: 10,
    imagen: '/images/hombre/INMOTION.jpg',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Naranja, albahaca, bergamota y hojas de violeta.',
    notaCorazon: ' Canela, pimienta rosa, cardamomo y nuez moscada.',
    notaBase: 'ándalo, vetiver, notas amaderadas y almizcle.',
    stock: 5,
    descripcion: 'Es una fragancia que equilibra la frescura cítrica con un toque especiado y cálido, diseñada para hombres seguros y en constante movimiento.',
    resenas: 312
  },
  {
    id: 58,
    nombre: 'AMBER OUD',
    marca: 'AL HARAMAIN',
    precio: 340.000,
    descuento: 10,
    imagen: '/images/hombre/HARAMAINA.jpg',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Oriental',
    volumen: 125,
    notaSalida: 'Bergamota y notas verdes',
    notaCorazon: 'Melón, piña y ámbar.',
    notaBase: ' Vainilla, almizcle y notas amaderadas.',
    stock: 8,
    descripcion: 'es una fragancia unisex de la familia olfativa Oriental Vainilla (o Ámbar Almizclada). Se caracteriza por un aroma intenso.',
    resenas: 298
  },
  {
    id: 59,
    nombre: '12 VIP BLACK',
    marca: 'Carolina Herrera',
    precio: 420.000,
    descuento: 10,
    imagen: '/images/hombre/212vipblack.jpg',
    rating: 4.9,
    genero: 'hombre',
    tipo: ' Fougere',
    volumen: 100,
    notaSalida: 'Absenta, anís e hinojo.',
    notaCorazon: ' Lavanda y cuero.',
    notaBase: 'Vainilla negra y almizcle.',
    stock: 5,
    descripcion: 'ideal para la noche y eventos sociales. Destaca por su aroma intenso, seductor y dulce.',
    resenas: 456
  },
  {
    id: 60,
    nombre: 'STARWALKER ',
    marca: 'Mont blanc',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/STAR.png',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 90,
    notaSalida: 'Mandarina, bambú y bergamota',
    notaCorazon: 'Sándalo, cedro y almizcle blanco.',
    notaBase: 'Nuez moscada, jengibre, ámbar y resina de abeto.',
    stock: 7,
    descripcion: 'La fragancia, creada por Michel Almairac, transmite una sensación de frescura y energía, con un diseño inspirado en el "hombre del mañana.',
    resenas: 234
  },
  {
    id: 61,
    nombre: '9PM',
    marca: 'Afnan',
    precio: 350.000,
    descuento: 10,
    imagen: '/images/hombre/9PMH.png',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Especiada',
    volumen: 100,
    notaSalida: 'Manzana, canela, lavanda silvestre y bergamota',
    notaCorazon: 'Flor de azahar del naranjo y lirio de los valles (muguete).',
    notaBase: 'Vainilla, haba tonka, ámbar y pachulí (',
    stock: 6,
    descripcion: 'Se caracteriza por un aroma dulce, intenso y seductor, ideal para la noche y climas fríos.',
    resenas: 523
  },
  {
    id: 62,
    nombre: 'Ligth Blue',
    marca: 'Dolce & Gabbana',
    precio: 390.000,
    descuento: 10,
    imagen: '/images/hombre/LBDGH.png',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Citrica',
    volumen: 100,
    notaSalida: 'Mandarina siciliana, bergamota, toronja, enebro de Virginia',
    notaCorazon: 'Romero, pimienta y palo de rosa de Brasil.',
    notaBase: 'Almizcle, incienso y musgo de roble.',
    stock: 6,
    descripcion:'Es una fragancia  cítrica aromática, icónica por su frescura mediterránea, perfecta para clima cálido y uso diario.',
    resenas: 278,
  },
  {
    id: 63,
    nombre: 'L 12.12 Blanc Pure',
    marca: 'Lacoste',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/BLANCLACOSTE.jpg',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Toronja (pomelo), romero y cardamomo.',
    notaCorazon: ' Ylang-ylang y nardos.',
    notaBase: 'Cedro de Virginia, cuero, gamuza y vetiver.',
    stock: 5,
    descripcion: 'Se caracteriza por un aroma limpio, fresco y cítrico con toques amaderados, es ideal para uso diario y climas cálidos.',
    resenas: 212
  },
  {
    id: 64,
    nombre: 'BAD BOY',
    marca: 'Carolina Herrera',
    precio: 440.000,
    descuento: 0,
    imagen: '/images/hombre/BADBOY.jpg',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Especiada',
    volumen: 100,
    notaSalida: 'Pimienta blanca, pimienta negra y bergamota verde italiana.',
    notaCorazon: 'Salvia y madera de cedro',
    notaBase: 'Haba tonka, cacao y Amberwood',
    stock: 8,
    descripcion: 'es una fragancia  para el hombre moderno, audaz y enérgico. Se caracteriza por un contraste explosivo de pimientas, bergamota, salvia, haba tonka y cacao, ofreciendo un aroma dulce, cálido y seductor.',
    resenas: 389
  },
  {
    id: 65,
    nombre: ' 212',
    marca: 'Carolina Herrera',
    precio: 460.000,
    descuento: 10,
    imagen: '/images/hombre/212H.png',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Especias, petit grain, lavanda, notas verdes, toronja y bergamota.',
    notaCorazon: 'Jengibre, pimienta verde, gardenia, violeta y salvia.',
    notaBase: 'Ládano, sándalo, almizcle, madera de gaiac, vetiver e incienso.',
    stock: 7,
    descripcion: 'Este perfume representa la energía de la ciudad de Nueva York, siendo una fragancia clásica que combina la frescura inicial con un fondo intenso y masculino',
    resenas: 445
  },
  {
    id: 66,
    nombre: 'ODYSSEY ELIXIR',
    marca: 'Armaf',
    precio: 380.000,
    descuento: 10,
    imagen: '/images/hombre/ODYSSEY.png',
    rating: 4.6,
    genero: 'hombre',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Mandarina, naranja, lavanda, cardamomo y pimienta negra.',
    notaCorazon: 'Caramelo, haba tonka, pachulí e incienso.',
    notaBase: 'Vainilla y vetiver.',
    stock: 9,
    descripcion: 'Es considerado un perfume moderno, adictivo y sofisticado con una excelente fijación.',
    resenas: 167
  },
  {
    id: 67,
    nombre: 'Invictus',
    marca: 'Paco Rabanne',
    precio: 450.000,
    descuento: 10,
    imagen: '/images/hombre/INVICTUS.png',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Pomelo, notas marinas y mandarina',
    notaCorazon: 'Hoja de laurel y jazmín',
    notaBase: 'Madera de gaiac, musgo de roble, pachulí y ámbar gris',
    stock: 8,
    descripcion: 'La fragancia es ideal para el uso diario o actividades físicas debido a su perfil fresco y duradero',
    resenas: 312
  },
  {
    id: 68,
    nombre: 'Eros Flame',
    marca: 'Versace',
    precio: 380.000,
    descuento: 10,
    imagen: '/images/hombre/EROSFLAME.png',
    rating: 4.6,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: ' Mandarina, chinotto, limón, pimienta negra y romero.',
    notaCorazon: 'Pimienta, geranio y rosa.',
    notaBase: 'Vainilla, haba tonka, cedro de Texas, sándalo, pachulí y musgo de roble.',
    stock: 11,
    descripcion: 'Eros Flame se distingue por ser más especiado y cálido que el Eros original, buscando equilibrar la pasión con la fuerza.',
    resenas: 189
  },
  {
    id: 69,
    nombre: 'Legend',
    marca: 'Mont Blanc',
    precio: 390.000,
    descuento: 0,
    imagen: '/images/hombre/LEGEND2.jpg',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Fougere',
    volumen: 100,
    notaSalida: 'Lavanda, bergamota, cedrón y piña',
    notaCorazon: 'Cumarina, musgo de roble, geranio, rosa, manzana roja y frutos secos.',
    notaBase: 'Sándalo y haba tonka.',
    stock: 6,
    descripcion: ' es ideal para uso diario por su perfil seductor, cítrico y amaderado que atrae cumplidos..',
    resenas: 267
  },
  {
    id: 70,
    nombre: 'Nautica Voyage',
    marca: 'Nautica',
    precio: 290.000,
    descuento: 15,
    imagen: '/images/hombre/VOYAGE.png',
    rating: 4.6,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Manzana verde y hojas verdes ',
    notaCorazon: 'Mimosa, flor de loto y notas marinas.',
    notaBase: 'Almizcle, cedro, musgo de roble y ámbar.',
    stock: 9,
    descripcion: 'Es considerada una de las mejores fragancias económicas para hombre, evocando libertad y energía marina.',
    resenas: 201
  },
  {
    id: 71,
    nombre: 'ASAD',
    marca: 'lATTAFA',
    precio: 290.000,
    descuento: 10,
    imagen: '/images/hombre/ASADH.png',
    rating: 4.7,
    genero: 'hombre',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Pimienta negra, tabaco, piña.',
    notaCorazon: ' Pachulí, café, iris',
    notaBase: 'Vainilla, ámbar, madera seca, benjuí, ládano.',
    stock: 6,
    descripcion: ' una alternativa económica con una alta similitud al popular perfume Dior Sauvage Elixir.  .',
    resenas: 223
  },
  {
    id: 72,
    nombre: 'Polo Blue',
    marca: 'Ralph Lauren',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/POLOBLUE.png',
    rating: 4.6,
    genero: 'hombre',
    tipo: 'Fougere',
    volumen: 100,
    notaSalida: 'Pepino, melón, mandarina',
    notaCorazon: 'Albahaca, salvia esclarea, geranio.',
    notaBase: 'Gamuza (ante), notas amaderadas, almizcle.',
    stock: 3,
    descripcion: 'Polo Blue representa frescura, libertad y un espíritu deportivo.',
    resenas: 178
  },
  {
    id: 73,
    nombre: 'One Essence',
    marca: 'Calvin klein',
    precio: 360.000,
    descuento: 10,
    imagen: '/images/hombre/onessence.png',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Citrica',
    volumen: 200,
    notaSalida: 'Bergamota italiana, naranja sanguina, té blanco y pimienta negra.',
    notaCorazon: 'Té verde orgánico, menta y geranio.',
    notaBase: 'Sándalo australiano, almizcle reciclado, incienso y musgo.',
    stock: 10,
    descripcion: 'Un aroma limpio pero con mayor profundidad que la versión original.',
    resenas: 289
  },
  {
    id: 74,
    nombre: 'Azzaro Wanted By Night',
    marca: 'Azzaro',
    precio: 385.000,
    descuento: 0,
    imagen: '/images/hombre/AZARO.jpg',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Canela, mandarina, lavanda y limón',
    notaCorazon: 'incienso, comino y cedro rojo japonés',
    notaBase: 'Tabaco, vainilla, cedro, cuero, benjuí, Iso E Super, ciprés y pachulí.',
    stock: 9,
    descripcion: 'Perfecto para la noche, citas románticas o ambientes de fiesta.',
    resenas: 334
  },
  {
    id: 75,
    nombre: 'Man In BLACK',
    marca: 'Bvlgari',
    precio: 450.000,
    descuento: 0,
    imagen: '/images/hombre/MANB.png',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Oriental',
    volumen: 100,
    notaSalida: 'Especias vibrantes, ron y tabaco.',
    notaCorazon: 'Cuero, nardos e iris.',
    notaBase: 'Madera de guayaco, benjuí y haba tonka.',
    stock: 4,
    descripcion: 'Esta fragancia está inspirada en el dios romano del fuego, Vulcano, buscando transmitir poder y una masculinidad moderna.',
    resenas: 456
  },
  {
    id: 76,
    nombre: 'SOLO LOEWE',
    marca: 'LOEWE',
    precio: 420.000,
    descuento: 0,
    imagen: '/images/hombre/SOLO.png',
    rating: 4.9,
    genero: 'hombre',
    tipo: 'Especiada',
    volumen: 100,
    notaSalida: 'Mandarina, guayaba, lavanda, limón, bergamota, madera de cachemira, romero, pachulí, tomillo y caña agria.',
    notaCorazon: 'Pimienta rosa, canela, naranja tangerina, aldehídos, nuez moscada, menta, alcaravea y anís.',
    notaBase: 'Ámbar, notas amaderadas, vainilla, almizcle y musgo de roble.',
    stock: 4,
    descripcion: 'Caracterizada por su contraste de notas opuestas: frescura cítrica contra calidez especiada.',
    resenas: 378
  },
  {
    id: 77,
    nombre: 'Blue Seduction',
    marca: 'Antonio Banderas',
    precio:290.000,
    descuento: 10,
    imagen: '/images/hombre/blue.png',
    rating: 4.9,
    genero: 'hombre',
    tipo: ' Fougere',
    volumen: 100,
    notaSalida: 'Bergamota, menta, grosellas negras y melón.',
    notaCorazon: 'Agua de mar, manzana verde, capuchino, cardamomo y nuez moscada.',
    notaBase: 'Ámbar y notas amaderadas.',
    stock: 9,
    descripcion: 'Es ideal para uso diario y climas cálidos por su aroma veraniego y versátil. .',
    resenas: 445
  },
  {
    id: 78,
    nombre: 'Lemale',
    marca: 'Jean Paul Gaultier',
    precio: 390.000,
    descuento:0 ,
    imagen: '/images/hombre/LEMALE.png',
    rating: 4.8,
    genero: 'hombre',
    tipo: 'Fougere',
    volumen: 100,
    notaSalida: 'Menta, lavanda, bergamota, cardamomo y abrótano.',
    notaCorazon: 'Canela, comino y flor de azahar del naranjo.',
    notaBase: 'Vainilla, haba tonka, ámbar, sándalo y cedro.',
    stock: 4,
    descripcion: 'Estilo Juvenil, seductor y con gran personalidad.',
    resenas: 234
  },
  {
    id: 79,
    nombre: 'Terre',
    marca: 'DHERMES',
    precio: 650.000,
    descuento: 0,
    imagen: '/images/hombre/terre.png',
    rating: 5.0,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Naranja, Toronja',
    notaCorazon: 'Pimienta, Pelargonio (geranio), Sílex.',
    notaBase: ' Vetiver, Cedro, Pachulí, Benjuí',
    stock: 5,
    descripcion: 'Estilo Sofisticado, natural, serio y atemporal, Perfecto para el uso diario en clima fresco o semiformal/formal.',
    resenas: 512
  },
  {
    id: 80,
    nombre: 'Club de nuit',
    marca: 'Armaf',
    precio: 380.00,
    descuento: 10,
    imagen: '/images/hombre/Clubnuit.png',
    rating: 5.0,
    genero: 'hombre',
    tipo: 'Amaderada',
    volumen: 100,
    notaSalida: 'Limón, piña, bergamota, grosellas negras y manzana',
    notaCorazon: 'Abedul, jazmín y rosa.',
    notaBase: 'Almizcle, ámbar gris, pachulí y vainilla.',
    stock: 4,
    descripcion: 'Versátil, elegante y seductor, con un toque ahumado distintivo.',
    resenas: 678
  }
]

export const useProductStore = create((set) => ({
  products: mockProducts,
  filteredProducts: mockProducts,
  loading: false,
  error: null,

  getAllProducts: () => set({ filteredProducts: mockProducts }),

  getProductById: (id) => {
    return mockProducts.find(p => p.id === parseInt(id)) || null
  },

  filterProducts: (filters) =>
    set((state) => {
    let filtered = [...mockProducts]

    if (filters.genero && filters.genero !== '') {
    filtered = filtered.filter(p => p.genero.toLowerCase() === filters.genero.toLowerCase())
      }

      if (filters.marca && filters.marca !== '') {
        filtered = filtered.filter(p => p.marca === filters.marca)
      }

      if (filters.tipo && filters.tipo !== '') {
        filtered = filtered.filter(p => p.tipo === filters.tipo)
      }

      if (filters.priceMin !== undefined && filters.priceMax !== undefined) {
        filtered = filtered.filter(
          p => p.precio >= filters.priceMin && p.precio <= filters.priceMax
        )
      }

      if (filters.search && filters.search !== '') {
        const searchLower = filters.search.toLowerCase()
        filtered = filtered.filter(
          p =>
            p.nombre.toLowerCase().includes(searchLower) ||
            p.marca.toLowerCase().includes(searchLower) ||
            p.descripcion.toLowerCase().includes(searchLower)
        )
      }

      if (filters.new === true) {
        filtered = filtered.slice(0, 3)
      }

        if (filters.discount === true) {
        filtered = filtered.filter(p => p.descuento > 0)
      }

      return { filteredProducts: filtered }
    }),

    sortProducts: (sortType) =>
    set((state) => {
      let sorted = [...state.filteredProducts]

      switch (sortType) {
        case 'precio-asc':
          sorted.sort((a, b) => a.precio - b.precio)
          break
        case 'precio-desc':
          sorted.sort((a, b) => b.precio - a.precio)
          break
        case 'rating':
          sorted.sort((a, b) => b.rating - a.rating)
          break
        case 'popular':
          sorted.sort((a, b) => b.resenas - a.resenas)
          break
        case 'newest':
          sorted = [...state.filteredProducts]
          break
        case 'descuento-desc':
          sorted.sort((a, b) => b.descuento - a.descuento)
          break
        default:
          break
      }

      return { filteredProducts: sorted }
    }),

  searchProducts: (query) =>
    set((state) => {
      if (!query || query.trim() === '') {
        return { filteredProducts: mockProducts }
      }

      const searchLower = query.toLowerCase()
      const filtered = mockProducts.filter(
        p =>
          p.nombre.toLowerCase().includes(searchLower) ||
          p.marca.toLowerCase().includes(searchLower) ||
          p.tipo.toLowerCase().includes(searchLower) ||
          p.descripcion.toLowerCase().includes(searchLower)
      )

      return { filteredProducts: filtered }
    }),
}))